server:
  port: 8080

spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/mysql?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:com.example.mymsg.dao/*.xml
  type-aliases-package: com.example.mymsg.entity

#showSql
logging:
  level:
    com:
      example:
         mymsg:
           dao : debug